In [13]:
#question1
import numpy as np
a= np.array([2,3,1,6,7])
for i in range(5):
    a[i]+=2
print(a)
for i in range(5):
    a[i]= a[i]*3
print(a)
for i in range(5):
    a[i]= a[i]/2
print(a)



[4 5 3 8 9]
[12 15  9 24 27]
[ 6  7  4 12 13]


In [23]:
#question2
arr= np.array([1, 2, 3, 6, 4, 5])
arr= arr[::-1]
print(arr)
x = np.array([1,2,3,4,5,1,2,1,1,1])
a= np.bincount(x)
mode1= np.argmax(a)
idx= np.where(x==mode1)[0]
print('most frequent value:',mode1)
print('indexes: ',idx)


x = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
a= np.bincount(x)
mode1= np.argmax(a)
idx= np.where(x==mode1)[0]
print('most frequent value:',mode1)
print('indexes: ',idx)



[5 4 6 3 2 1]
most frequent value: 1
indexes:  [0 5 7 8 9]
most frequent value: 1
indexes:  [0 1 2]


In [29]:
#question3
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [33]:
#question4
import numpy as np;
arr = np.array(np.linspace(10,100,25))
print("Original array is: ",arr,"\n")
print("Dimension of array is: ",arr.ndim,"\n")
print("Shape of array is: ",arr.shape,"\n")
print("Size of array is: ",arr.size,"\n")
print("Data type of data stored in array is: ",arr.dtype,"\n")
print("No of bytes required to store data in array is: ",arr.nbytes,"\n")
transpose = arr.reshape(-1,1)
print("Array transpose is: \n",transpose,"\n")
#print(arr.T)

Original array is:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ] 

Dimension of array is:  1 

Shape of array is:  (25,) 

Size of array is:  25 

Data type of data stored in array is:  float64 

No of bytes required to store data in array is:  200 

Array transpose is: 
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]] 

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [35]:
#question5
import numpy as np
ucs420 = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print("Original 2-D array is: \n",ucs420,"\n")
print("Mean of 2-D array is: ",np.mean(ucs420),"\n")
print("Median of 2-D array is: ",np.median(ucs420),"\n")
print("Maximum element of 2-D array is: ",np.max(ucs420),"\n")
print("Minimum element of 2-D array is: ",np.min(ucs420),"\n")
print("All unique element of 2-D array is: ",np.unique(ucs420),"\n")
reshaped_ucs420 = ucs420.reshape(4,3)
print("2-D array after reshaping to 4 rows and 3 columns is: \n",reshaped_ucs420,"\n")
resized_ucs420 = np.resize(ucs420,(2,3))
print("2-D array after resizing to 2 rows and 3 columns is: \n",resized_ucs420)

Original 2-D array is: 
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]] 

Mean of 2-D array is:  43.333333333333336 

Median of 2-D array is:  37.5 

Maximum element of 2-D array is:  90 

Minimum element of 2-D array is:  10 

All unique element of 2-D array is:  [10 15 20 30 35 40 50 60 70 80 90] 

2-D array after reshaping to 4 rows and 3 columns is: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]] 

2-D array after resizing to 2 rows and 3 columns is: 
 [[10 20 30]
 [40 50 60]]
